# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Booru-chan' do
	pod 'SWXMLHash'
	pod 'SwiftyJSON'
	pod 'Alamofire', '3.1.0'
end

target 'Booru-chanTests' do

end

target 'Booru-chanUITests' do

end

